---
stages:
  - build

build:
  stage: build
  script:
    - VERSION="$(< VERSION)"
    - docker build --build-arg COMMIT_HASH="${CI_COMMIT_SHA}" --build-arg VERSION="${VERSION}" -t policy-as-code-demo .
