---
stages:
  - build
  - test

build:
  stage: build
  script:
    - VERSION="$(< VERSION)"
    - docker build --build-arg COMMIT_HASH="${CI_COMMIT_SHA}" --build-arg VERSION="${VERSION}" -t policy-as-code-demo .

test-iac:
  stage: test
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  script:
    - cd iac
    - "terraform init -backend=false"
    - terraform validate

smoke-test:
  stage: test
  script:
    - docker run policy-as-code-demo

test-iac:
  stage: test
  image:
    name: seiso/easy_infra:2023.10.06-terraform
    entrypoint: [""]
  script:
    - cd iac
    - "terraform init -backend=false"
    - terraform validate
